[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css" 